name=ESP_CountFreq
version=1.0.2
author=EA2EBK
maintainer=ea2ebk@gmail.com
sentence=Librería para medir frecuencia en el ESP32-S3 utilizando el periférico PCNT.
paragraph=Esta librería permite contar pulsos en un pin PCNT_IMPUT_PIN del ESP32-S3 utilizando el periférico PCNT y un timer para medir la frecuencia de la señal.
category=Signal Processing
url=https://github.com/LECA_EA/ESP_CountFreq
architectures=esp32
license=MIT
depends=esp32
